# Generated by Django 2.1.15 on 2020-05-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tole_view',
            new_name='total_view',
        ),
    ]
